version: '3.4'

services:

  collector:
    restart: always
    environment:
      - DB_HOST=db
      - BROKER_HOST=broker

  db:
    restart: always
    ports:
      - "27017:27017"

  broker:
    restart: always
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf
