version: '3.4'

services:

  collector:
    image: ${DOCKER_REGISTRY-}datacollector
    build:
      context: .
      dockerfile: DataCollector/Dockerfile
      args:
        - GITHUB_PACKAGE_TOKEN
    depends_on:
      - db

  db:
    image: mongo

  broker:
    image: eclipse-mosquitto
