version: '3.4'

services:

  collector:
    restart: always
    environment:
      - DB_CONNECTION=mongodb://root:${DB_PASSWORD}@db
      - BROKER_HOST=broker

  db:
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  broker:
    restart: always
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf
