name: .NET

on:
  push:
    paths-ignore:
      - 'Arduino/**'

jobs:
  build:

    runs-on: windows-latest

    env:
      GITHUB_PACKAGE_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: |
        dotnet build DeviceConfig.sln
        dotnet build DataCollector.sln
